#!/usr/bin/env bash

rm -rf target
mkdir target
cd target
cp ../test/test-* .
cat test-split-a >>test-output
../md5incremental test-output test-done &
sleep 1
cat test-split-b >>test-output; sleep 1
cat test-split-c >>test-output; sleep 1
cat test-split-d >>test-output; sleep 1
touch test-done
wait
md5sum test-input test-output
