#!/usr/bin/env bash

rm -rf target
mkdir target
cd target
cp ../test/test-* .

fake-dd() {
    cat test-split-a >>test-output
    sleep 0.2
    cat test-split-b >>test-output; sleep 0.2
    cat test-split-c >>test-output; sleep 0.2
    cat test-split-d >>test-output; sleep 0.2
}

verify-copy() {
    ../md5incremental test-output test-done >test-output.md5
    sed 's/input/output/' test-input.md5 | diff - test-output.md5
}

(fake-dd; touch test-done) &
verify-copy
