#!/usr/bin/env python

"""Tool to incrementally read a growing file, computing an md5 checksum.
Will continuously (every second) look for the existence of a "control file",
which signals that the input file is complete.

Typical invocation (in a separate shell):

    md5incremental input_file control_file

Client code will typically trigger execution halt and md5 output like this:

    touch control_file
"""

import argparse


def main():
    args = parse_args()
    run(args)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input_file', help='the growing file to checksum')
    parser.add_argument('control_file', help='which file triggers "done"')
    args = parser.parse_args()
    return args


def run(args):
    """Primary point of execution."""
    print 'hello world'
    print args


if __name__ == '__main__':
    main()
