#!/usr/bin/env python

"""Tool to incrementally read a growing file, computing an md5 checksum.
Will continuously (every second) look for the existence of a "control file",
which signals that the input file is complete.

Typical invocation (in a separate shell):

    md5incremental input_file control_file

Client code will typically trigger execution halt and md5 output like this:

    touch control_file
"""

import argparse
import hashlib
import os
import time


BLOCK_SIZE = 4096

def main():
    args = parse_args()
    run(args)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input_file', help='the growing file to checksum')
    parser.add_argument('control_file', help='which file triggers "done"')
    args = parser.parse_args()
    return args


def run(args):
    """Primary point of execution."""
    print 'hello world'
    print args
    md5 = hashlib.md5()
    with open(args.input_file) as file_in:
        while True:
            data = file_in.read(BLOCK_SIZE)
            if data:
                md5.update(data)
            else:  # Have hit end of file (possibly just for now...)
                if os.path.exists(args.control_file):
                    break
                else:
                    print 'hiccup'
                    time.sleep(0.5)
                    file_in.seek(file_in.tell())
    print md5.hexdigest()
    print 'all done'


if __name__ == '__main__':
    main()
